extends SceneTree
const Network=preload("res://scripts/streets_model.gd")
const Utilities=preload("res://scripts/city_utilities.gd")
const Resources=preload("res://scripts/water_resources.gd")
func flat(_x:float,_z:float)->float:return 0.5
func add(model,point:Vector2,zone:String,tier:String="small")->Dictionary:
	var candidate:Dictionary=model.housing.candidate(point,model.roads,flat,zone,tier,zone+"_"+tier if Utilities.is_service(zone) else "")
	assert(not candidate.is_empty(),"Cabe: "+zone+str(point))
	assert(model.place_lot(candidate).ok)
	return model.housing.lots[-1]
func reload(model):
	var result=Network.restore(JSON.parse_string(JSON.stringify(model.serialize())))
	assert(result!=null and result.cash==model.cash)
	assert(result.housing.economy.account_total(result.housing)==0)
	return result
func _initialize()->void:
	var model=Network.new()
	assert(model.commit(Vector2(-80,0),Vector2(70,0)))
	add(model,Vector2(-64,9),"power")
	add(model,Vector2(-42,9),"water")
	var home:=add(model,Vector2(-20,9),"residential")
	var factory:=add(model,Vector2(0,-9),"industrial")
	model.simulate(25)
	assert(home.demand_pending and factory.demand_pending,"Água e energia não substituem esgoto")
	assert(not home.sewer_exempt)
	assert(Utilities.state(home,Utilities.budget(model.housing)).text.contains("esgoto"))
	var plant:=add(model,Vector2(20,9),"sewage")
	assert(Utilities.budget(model.housing).sewage==0)
	model.simulate(50)
	assert(home.stage==2 and factory.stage==2 and plant.stage==2)
	var supply:=Utilities.budget(model.housing)
	assert(supply.sewage==30 and supply.sewage_generated==4 and supply.sewage_treated==4 and supply.sewage_untreated==0)
	assert(supply.sewage_used==4 and supply.sewage_external==0)
	assert(Utilities.state(factory,supply).operational)
	reload(model)
	var before:int=model.cash
	var population:int=model.housing.residents.size()
	assert(model.demolish_lot(plant.id).ok)
	assert(model.cash==before and model.housing.residents.size()==population)
	supply=Utilities.budget(model.housing)
	assert(supply.sewage==0 and supply.sewage_untreated==4 and supply.sewage_treated==0)
	assert(not factory.operational and supply.alerts>=2)
	var person:Dictionary=model.housing.residents[0]
	var balance:int=person.balance
	model.housing.economy.work_visit(person,factory)
	assert(person.balance==balance,"Falta esgoto interrompe atividade econômica")
	reload(model)
	add(model,Vector2(20,9),"sewage")
	model.simulate(24.1)
	assert(factory.operational and Utilities.budget(model.housing).sewage_untreated==0)
	# Área seca rejeitada na prévia; transação revalida mesmo uma geometria forjada.
	assert(Resources.field_at(Vector2(70,-70))==-1)
	assert(model.commit(Vector2(70,0),Vector2(70,-80)))
	var dry:Dictionary=model.housing.candidate(Vector2(61,-70),model.roads,flat,"power","small")
	assert(not dry.is_empty())
	dry.zone="water"
	dry.catalog_id="water_small"
	before=model.cash
	assert(not model.place_lot(dry).ok and model.cash==before)
	assert(model.housing.candidate(Vector2(61,-70),model.roads,flat,"water","small").is_empty())
	# Dois poços no mesmo aquífero respeitam o limite mesmo em redes separadas.
	var shared=Network.new()
	assert(shared.commit(Vector2(-80,0),Vector2(-50,0)))
	assert(shared.commit(Vector2(-50,0),Vector2(-44,0)))
	assert(shared.commit(Vector2(-44,0),Vector2(70,0)))
	var first:=add(shared,Vector2(-64,11),"water","large")
	var second:=add(shared,Vector2(-30,11),"water","large")
	shared.simulate(25)
	supply=Utilities.budget(shared.housing)
	assert(supply.water==180 and supply.resources.sources[first.id].amount==180 and supply.resources.sources[second.id].amount==0)
	assert(not Utilities.state(second,supply).operational)
	assert(shared.demolish_road(shared.pick_demolition_road(Vector2(-47,0))).ok)
	supply=Utilities.budget(shared.housing)
	assert(supply.water==180 and supply.resources.used[0]==180)
	assert(Utilities.component(first,supply)!=Utilities.component(second,supply))
	reload(shared)
	assert(shared.demolish_lot(first.id).ok)
	supply=Utilities.budget(shared.housing)
	assert(supply.water==180 and supply.resources.sources[1].amount==180,"Remover poço libera vazão para o próximo")
	reload(shared)
	# Migração real de 0.0.15: sem cobrar de novo nem interromper atendimento.
	var data:Dictionary=JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/city-0.0.15.json"))
	var migrated=Network.restore(data)
	assert(migrated!=null and migrated.cash==data.cash)
	assert(migrated.housing.economy.public_works_spent==data.residential.economy.public_works_spent)
	for lot in migrated.housing.lots:
		assert(lot.sewer_exempt)
		if lot.zone=="water": assert(lot.source_legacy)
	var persisted:Dictionary=migrated.serialize()
	assert(persisted.residential.sanitation_version==1)
	persisted.residential.lots[0].erase("sewer_exempt")
	assert(Network.restore(persisted)==null,"Novo save não perde campos para recuperar isenção")
	reload(migrated)
	print("CITY_SANITATION_OK: captação, aquífero compartilhado, coleta, tratamento, interrupção, reconexão, orçamento e migração 0.0.15")
	quit()
