extends SceneTree
const Network=preload("res://scripts/streets_model.gd")
const Problems=preload("res://scripts/city_problems.gd")
const Economy=preload("res://scripts/economy.gd")
func flat(_x:float,_z:float)->float:return 0.5
func add(model,point:Vector2,zone:String,tier:String="small")->Dictionary:
	var lot:Dictionary=model.housing.candidate(point,model.roads,flat,zone,tier,zone+"_"+tier if zone in ["water","power","sewage"] else "")
	assert(not lot.is_empty(),zone+str(point))
	assert(model.place_lot(lot).ok)
	return model.housing.lots[-1]
func reload(model):
	var out=Network.restore(JSON.parse_string(JSON.stringify(model.serialize())))
	assert(out!=null and out.cash==model.cash and out.housing.economy.account_total(out.housing)==0)
	return out
func _initialize()->void:
	var model=Network.new()
	assert(model.commit(Vector2(-80,0),Vector2(70,0)))
	var home:=add(model,Vector2(-20,9),"residential")
	var factory:=add(model,Vector2(-5,9),"industrial")
	var before:=JSON.stringify(model.serialize())
	var snapshot:=Problems.capture(model)
	assert(snapshot.counts.all==2 and snapshot.counts.services==2 and snapshot.causes==6)
	assert(Problems.filtered(snapshot,"access").is_empty())
	assert(snapshot.entries[0].issues[0].code=="water")
	assert(JSON.stringify(model.serialize())==before,"Diagnóstico não altera a simulação")
	add(model,Vector2(-64,9),"power")
	add(model,Vector2(-42,9),"water")
	var plant:=add(model,Vector2(20,9),"sewage")
	model.simulate(50)
	assert(home.stage==2 and factory.stage==2 and Problems.capture(model).counts.all==0)
	# Orçamento realizado, estimativa e conservação da contabilidade.
	var cash:int=model.cash
	model.simulate(130.1)
	var detail:Dictionary=model.budget_details()
	assert(detail.known and detail.last_breakdown=={"roads":8,"water":20,"power":30,"sewage":25,"unclassified":0})
	assert(detail.last.maintenance==83 and model.cash==cash+detail.last.net)
	assert(detail.active==detail.authorized and detail.active_net==detail.last.taxes-83)
	reload(model)
	# Histórico não muda ao demolir; estimativas e contadores mudam imediatamente.
	var recorded:Dictionary=detail.last_breakdown.duplicate(true)
	assert(model.demolish_lot(plant.id).ok)
	detail=model.budget_details()
	assert(detail.last_breakdown==recorded and detail.active.sewage==0 and detail.counts.sewage.ready==0)
	var extra:=add(model,Vector2(50,11),"power","large")
	detail=model.budget_details()
	assert(detail.active.power==30 and detail.authorized.power==150 and detail.counts.power.works==1)
	assert(detail.active_net-detail.authorized_net==120)
	reload(model)
	snapshot=Problems.capture(model)
	assert(snapshot.counts.services==2 and snapshot.entries[0].issues[0].code=="sewage")
	var old_target:Dictionary=snapshot.entries[1]
	assert(model.demolish_lot(home.id).ok)
	var target:Dictionary=Problems.find_target(model,old_target)
	assert(not target.is_empty() and target.id==1 and target.zone=="industrial","Renumerar mantém o endereço do botão")
	assert(model.demolish_lot(1).ok and Problems.find_target(model,old_target).is_empty())
	# Desconexão tem precedência: resolver acesso em vez de sugerir várias instalações.
	assert(model.demolish_road(model.pick_demolition_road(Vector2(30,0))).ok)
	snapshot=Problems.capture(model)
	assert(snapshot.counts.access==model.housing.lots.size())
	for entry in snapshot.entries:assert(entry.issues.size()==1 and entry.issues[0].code=="access")
	reload(model)
	# Demanda sem carência de serviços continua explicando a espera.
	var demand_model=Network.new()
	assert(demand_model.commit(Vector2(-80,0),Vector2(70,0)))
	add(demand_model,Vector2(-64,9),"power","medium")
	add(demand_model,Vector2(-42,9),"water","medium")
	add(demand_model,Vector2(20,9),"sewage","medium")
	for x in [-64,-48,-32,-16,0,16]:add(demand_model,Vector2(x,-9),"residential")
	demand_model.simulate(50)
	snapshot=Problems.capture(demand_model)
	assert(snapshot.counts.demand>0 and snapshot.counts.services==0)
	assert(Problems.filtered(snapshot,"demand")[0].issues[0].action.contains("vagas"))
	# Empresa sem moradores explica falta de trabalhadores e limpa aviso após contratar.
	var staffing=Network.new()
	assert(staffing.commit(Vector2(-80,0),Vector2(70,0)))
	add(staffing,Vector2(-64,9),"power")
	add(staffing,Vector2(-42,9),"water")
	add(staffing,Vector2(20,9),"sewage")
	add(staffing,Vector2(0,9),"industrial")
	staffing.simulate(50)
	snapshot=Problems.capture(staffing)
	assert(snapshot.counts.demand==1 and snapshot.entries[0].issues[0].code=="workers")
	add(staffing,Vector2(40,9),"residential")
	staffing.simulate(24.1)
	assert(Problems.capture(staffing).counts.all==0)
	# Vazão parcial é aviso; vazão zero tem prioridade maior.
	var resource_model=Network.new()
	assert(resource_model.commit(Vector2(-80,0),Vector2(70,0)))
	add(resource_model,Vector2(-50,9),"water")
	add(resource_model,Vector2(-25,11),"water","large")
	add(resource_model,Vector2(-65,11),"water","large")
	resource_model.simulate(25)
	snapshot=Problems.capture(resource_model)
	assert(snapshot.counts.services==2 and snapshot.entries[0].severity==2 and snapshot.entries[1].severity==1)
	assert(snapshot.entries[1].issues[0].title.contains("150/180"))
	# Atendimento local não substitui acesso externo necessário aos empreendimentos.
	var isolated=Network.new()
	assert(isolated.commit(Vector2(-80,0),Vector2(-20,0)))
	assert(isolated.commit(Vector2(-20,0),Vector2(0,0)))
	assert(isolated.commit(Vector2(0,0),Vector2(70,0)))
	add(isolated,Vector2(40,9),"water")
	add(isolated,Vector2(60,9),"power")
	add(isolated,Vector2(20,9),"sewage")
	add(isolated,Vector2(30,-9),"industrial")
	add(isolated,Vector2(50,-9),"residential")
	isolated.simulate(50)
	assert(isolated.demolish_road(isolated.pick_demolition_road(Vector2(-10,0))).ok)
	snapshot=Problems.capture(isolated)
	assert(snapshot.counts.access==2 and snapshot.counts.services==0)
	for entry in snapshot.entries:assert(entry.issues[0].code=="isolated")
	# Fixture real da 0.0.16: despesa antiga não pode ser atribuída por suposição.
	var data:Dictionary=JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/city-0.0.16.json"))
	var migrated=Network.restore(data)
	assert(migrated!=null and migrated.cash==data.cash)
	detail=migrated.budget_details()
	assert(not detail.known and detail.last_breakdown.unclassified==data.residential.economy.last.maintenance)
	assert(detail.last_breakdown.water==0 and detail.active.water>0)
	migrated=reload(migrated)
	migrated.simulate(migrated.housing.economy.DAY_SECONDS-migrated.housing.economy.elapsed)
	assert(migrated.housing.economy.last_breakdown_known and migrated.housing.economy.last_maintenance.unclassified==0)
	migrated=reload(migrated)
	var bad:Dictionary=migrated.serialize()
	bad.residential.economy.last_maintenance.water+=1
	assert(Network.restore(bad)==null)
	bad=migrated.serialize()
	bad.residential.economy.last_breakdown_known="true"
	assert(Network.restore(bad)==null)
	bad=migrated.serialize()
	bad.residential.economy.last_maintenance.sewage=-1
	assert(Network.restore(bad)==null)
	print("PROBLEMS_BUDGET_OK: causas, filtros, recuperação, renumeração, orçamento histórico/estimado, contas e migração 0.0.16")
	quit()
