extends SceneTree
const Network = preload("res://scripts/streets_model.gd")
const Housing = preload("res://scripts/residential.gd")
const Store = preload("res://scripts/city_store.gd")
func _initialize() -> void:
	call_deferred("_run")
func flat(_x: float,_z: float) -> float:
	return 0.5
func build(model, point: Vector2, zone: String, size_mode: String) -> Dictionary:
	var lot: Dictionary = model.housing.candidate(point,model.roads,flat,zone,size_mode)
	assert(not lot.is_empty())
	lot["utility_exempt"]=true # Isola a regra anterior; infraestrutura tem teste próprio.
	model.housing.commit(lot)
	return lot
func _run() -> void:
	# Entre vias paralelas a 16 m, apenas os lotes de 6 m de profundidade cabem.
	var narrow = Network.new()
	assert(narrow.commit(Vector2(-80,0),Vector2(60,0)))
	assert(narrow.commit(Vector2(-60,0),Vector2(-60,16)))
	assert(narrow.commit(Vector2(-60,16),Vector2(60,16)))
	assert(narrow.housing.candidate(Vector2(0,8),narrow.roads,flat,"residential","large").is_empty())
	var small: Dictionary = narrow.housing.candidate(Vector2(0,8),narrow.roads,flat)
	assert(small.width == 4 and small.depth == 6,"Automático deve aproveitar o corredor estreito")
	small["utility_exempt"]=true # Isola a regra anterior; infraestrutura tem teste próprio.
	narrow.housing.commit(small)
	var adjacent := build(narrow,Vector2(6,8),"commercial","small")
	assert(Geometry2D.intersect_polygons(Housing.polygon(small),Housing.polygon(adjacent)).is_empty())
	assert(not Housing.road_conflict(small,narrow.roads))
	var cancelled: Dictionary = narrow.housing.candidate(Vector2(12,8),narrow.roads,flat,"industrial","small")
	assert(not cancelled.is_empty() and narrow.housing.lots.size() == 2,"Prévia não ocupa lote")
	# Modelos não podem ultrapassar o lote (exceto ligação frontal até a via).
	var view = preload("res://scripts/buildings_view.gd").new()
	root.add_child(view)
	narrow.housing.advance(24)
	view.rebuild(narrow.housing.lots)
	assert(narrow.housing.residents.size() == 2)
	assert(narrow.housing.economy.account_total(narrow.housing) == 0)
	# Ciclo econômico real e persistente.
	var model = Network.new()
	assert(model.commit(Vector2(-80,0),Vector2(60,0)))
	build(model,Vector2(-40,11),"residential","large")
	build(model,Vector2(-20,11),"residential","medium")
	build(model,Vector2(0,11),"commercial","medium")
	build(model,Vector2(20,11),"industrial","large")
	model.housing.advance(24)
	assert(model.housing.economy.employment_count(model.housing) > 0)
	var road_cash: int = model.cash
	model.simulate(model.housing.economy.DAY_SECONDS)
	assert(model.housing.economy.day == 1)
	assert(model.housing.economy.last.wages > 0 and model.housing.economy.last.exports > 0)
	assert(model.housing.economy.last.sales > 0 and model.housing.economy.last.taxes > 0)
	assert(model.cash == road_cash + model.housing.economy.last.net)
	assert(model.housing.economy.account_total(model.housing) == 0,"Transferências devem conservar dinheiro")
	model.simulate(model.housing.economy.DAY_SECONDS-0.5)
	var store = Store.new()
	store.base_path = "user://zoning_economy_test.json"
	assert(store.save_city(42,model))
	var restored = Network.restore(store.load_city())
	assert(restored != null)
	assert(restored.housing.economy.day == 1)
	assert(is_equal_approx(restored.housing.economy.elapsed,restored.housing.economy.DAY_SECONDS-0.5))
	restored.simulate(0.5)
	assert(restored.housing.economy.day == 2,"Recarga completa apenas o dia pendente")
	restored.simulate(0)
	assert(restored.housing.economy.day == 2,"Não creditar o mesmo dia duas vezes")
	for day in range(60):
		restored.simulate(restored.housing.economy.DAY_SECONDS)
		assert(restored.housing.economy.account_total(restored.housing) == 0)
	assert(store.save_city(42,restored))
	assert(Network.restore(store.load_city()) != null)
	# Migração de um arquivo efetivamente produzido pela 0.0.7.
	var legacy: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/city-0.0.7.json"))
	var migrated = Network.restore(legacy)
	assert(migrated != null)
	assert(migrated.cash == int(legacy.cash))
	assert(migrated.housing.residents.size() == legacy.residential.residents.size())
	assert(migrated.housing.lots[0].width == 10 and migrated.housing.lots[0].depth == 12)
	assert(migrated.housing.lots[1].stage == 1,"Preservar obra em andamento")
	assert(migrated.housing.economy.account_total(migrated.housing) == 0)
	assert(store.save_city(42,migrated))
	var migrated_again = Network.restore(store.load_city())
	assert(migrated_again != null)
	assert(migrated_again.housing.economy.exterior_balance == migrated.housing.economy.exterior_balance,"Migração não repete capital inicial")
	# Lotes nivelados reproduzíveis sem modificar a pista.
	var terrain = preload("res://scripts/landscape.gd").new()
	root.add_child(terrain)
	terrain.generate(42)
	terrain.clear_roads(narrow.roads)
	var road_before: float = terrain.height_at(0,0)
	terrain.set_lots(narrow.housing.lots)
	assert(is_equal_approx(terrain.height_at(small.x,small.z),small.height-0.06))
	assert(is_equal_approx(road_before,terrain.height_at(0,0)),"Nivelamento do lote não altera a pista")
	view.free()
	terrain.free()
	print("ZONING_ECONOMY_OK: espaços estreitos, tamanhos, empregos, contas, recarga e migração 0.0.7")
	quit()
